# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Update Leetcode status

on:
  schedule:
    - cron: '0 20 * * *'
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run LC tool
        env: 
          LCTOOL_LEETCODE_USERNAME: ${{ secrets.LCTOOL_LEETCODE_USERNAME }}
          LCTOOL_LEETCODE_PASSWORD: ${{ secrets.LCTOOL_LEETCODE_PASSWORD }}
        run: |
          wget -O lc-tool.tar.gz https://github.com/EINDEX/leetcode-spider-go/releases/download/v1.0.2/lc-tool-v1.0.2-linux-amd64.tar.gz
          tar -zxvf lc-tool.tar.gz
          ./lc-tool
      
      - name: Git update
        run: |
          git add .
          git push -r
